version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: seo_postgres
    restart: always 
    environment:
      POSTGRES_DB: seo_audit
      POSTGRES_USER: younes
      POSTGRES_PASSWORD: secret_password123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - seo_network

  redis:
    image: redis:7-alpine
    container_name: seo_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - seo_network

  api:
    build:
      context: ./api-symfony
      dockerfile: Dockerfile
    container_name: seo_symfony_api
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./api-symfony:/var/www/html
    environment:
      DATABASE_URL: "postgresql://younes:secret_password123@db:5432/seo_audit?serverVersion=16&charset=utf8"
      MESSENGER_TRANSPORT_DSN: "redis://redis:6379/messages"
    depends_on:
      - db
      - redis
    networks:
      - seo_network

  analyzer:
    build:
      context: ./analyzer-python
      dockerfile: Dockerfile
    container_name: seo_python_analyzer
    restart: always
    ports:
      - "8001:8000"
    volumes:
      - ./analyzer-python:/app
    environment:
      DATABASE_URL: "postgresql://younes:secret_password123@db:5432/seo_audit"
      REDIS_URL: "redis://redis:6379/0"
    env_file:
      - analyzer-python/.env
  
    depends_on:
      - db
      - redis
    networks:
      - seo_network
  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    container_name: seo_react_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-react:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - seo_network
networks:
  seo_network:
    driver: bridge

volumes:
  pgdata:


