<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260810202737 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE email_verification_codes ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE email_verification_codes ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE email_verification_codes ALTER verified DROP DEFAULT');
        $this->addSql('ALTER TABLE email_verification_codes ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER INDEX email_verification_codes_email_key RENAME TO UNIQ_7E033C11E7927C74');
        $this->addSql('ALTER TABLE users ALTER is_verified DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE email_verification_codes ALTER id SET DEFAULT nextval(\'email_verification_codes_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE email_verification_codes ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE email_verification_codes ALTER verified SET DEFAULT false');
        $this->addSql('ALTER TABLE email_verification_codes ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER INDEX uniq_7e033c11e7927c74 RENAME TO email_verification_codes_email_key');
        $this->addSql('ALTER TABLE users ALTER is_verified SET DEFAULT false');
    }
}
