# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html
# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    app_frontend_url: '%env(APP_FRONTEND_URL)%'
    app_mail_from: '%env(APP_MAIL_FROM)%'
    python_analyzer_base_url: 'http://analyzer:8000'
    reports_directory: '%kernel.project_dir%/var/reports'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Service\AuditPipelineOrchestrator:        
        arguments:
            $pythonAnalyzerBaseUrl: '%python_analyzer_base_url%'
    
    App\Controller\AuditPageHeadingImportController:
        arguments:
            $pythonAnalyzerBaseUrl: '%python_analyzer_base_url%'

    App\Service\AuditReportGenerator:
        arguments:
            $reportsDirectory: '%reports_directory%'