security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login_check
            stateless: true
            json_login:
                check_path: /api/login_check
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            jwt: ~

   
    access_control:
            # Public endpoints
            - { path: '^/api/login_check', roles: PUBLIC_ACCESS }
            - { path: '^/api/login', roles: PUBLIC_ACCESS }
            - { path: '^/api/docs', roles: PUBLIC_ACCESS }
            - { path: '^/api$', roles: PUBLIC_ACCESS }
            
            # Audit endpoints public
            - { path: '^/api/audit/callback$', roles: PUBLIC_ACCESS }
            - { path: '^/api/audit/check$', roles: PUBLIC_ACCESS }
            - { path: '^/api/audit/callback$', roles: PUBLIC_ACCESS }
            - { path: '^/api/audit/check$', roles: PUBLIC_ACCESS }
            - { path: '^/api/audit-page/import$', roles: PUBLIC_ACCESS }
            - { path: '^/api/audit-page-heading/import$', roles: PUBLIC_ACCESS }
            - { path: '^/api/audit-page-image/import$', roles: PUBLIC_ACCESS }
            - { path: '^/api/audit-keyword-density/import$', roles: PUBLIC_ACCESS }

            
            # All other /api endpoints require authentication
            - { path: '^/api', roles: IS_AUTHENTICATED_FULLY }